#!/bin/bash
echo "正在初始化配置......"
if [ ! -e $HOME/.config/jshellscript ];then mkdir -p $HOME/.config/jshellscript;fi
if [ ! -e $HOME/.config/jshellscript/bin ];then mkdir -p $HOME/.config/jshellscript/bin;fi

cp ./myshellscript.sh $HOME/.config/jshellscript
cp ./myother.sh $HOME/.config/jshellscript
cp ./my_env.env $HOME/.config/jshellscript

echo "初始化配置结束....."
